<a href="https://colab.research.google.com/github/HugocamposL3/Linguagem-Python-Para-Data-Science/blob/main/Aula_6_de_LPP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Aula 06 importação de biblioteca


## Exemplo 1

In [ ]:
#Importação da Biblioteca
import numpy as np ## Importei a biblioteca e dei nomenclatura como 'np'

In [ ]:
novo_array = np.array([[1,2,3],[4,5,6]]) # Para criar uma matriz com 2 vetores e 2 dimensões
print("abaixo está o seu array")
print(novo_array)

abaixo está o seu array
[[1 2 3]
 [4 5 6]]


##Ndim

In [ ]:
print(f"Esse é um ndarray com {novo_array.ndim} dimensões")

Esse é um ndarray com 2 dimensões


##Shape

In [ ]:
print(f"As dimensões desse ndarray possuem os seguintes tamanhos: {novo_array.shape}") # Para saber o tamanho do meu array 
print(f"Esse ndarray tem: {novo_array.shape[0]} Linhas e {novo_array.shape[1]} Colunas") # Para selecionar uma parte dessa tupla que o .shape vai me mostrar 

As dimensões desse ndarray possuem os seguintes tamanhos: (2, 3)
Esse ndarray tem: 2 Linhas e 3 Colunas


##Size

In [ ]:
print(f"Ao todo, esse ndarray contem {novo_array.size} elementos") # Quantidade de elementos que você vai ter no seu array

Ao todo, esse ndarray contem 6 elementos


##dtype

In [ ]:
print(f"Os elementos presentes nesse ndarray: {novo_array.dtype}") # "int64" é um inteiro com 64 bits

Os elementos presentes nesse ndarray: int64


## itemsize

In [ ]:
print(f"Os elementos presentes nesse array ocupam {novo_array.itemsize} bytes")

Os elementos presentes nesse array ocupam 8 bytes


## Exemplo 2

##Convertendo um tupla para array 

In [ ]:
array_tuplas = np.array([(1,2,3),(4,5,6)])
print(f"A nosso array de tuplas é composta por \n{array_tuplas}") ## Isso é importante para que ninguém mude os valores iniciais do seu array.

A nosso array de tuplas é composta por 
[[1 2 3]
 [4 5 6]]


In [ ]:
array_lista = np.array([[1,2,3], [4,5,6]])
print(f"a nossa array de lista é composta por \n {array_lista}")

a nossa array de lista é composta por 
 [[1 2 3]
 [4 5 6]]


## Exemplo 3

##np.zeros

In [ ]:
array_zerado = np.zeros((3,4)) ## Para criar um array somente com zeros com 3 linhas e 4 colunas
print(f"Este é minha matriz de zeros \n {array_zerado}")
print(f"O tipo da minha matriz é: {array_zerado.dtype}")

Este é minha matriz de zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
O tipo da minha matriz é: float64


##np.ones

In [ ]:
array_de_uns = np.ones((5,2),dtype = np.int32) ## Tranformando float para int
print(f"Esta é minha matriz de uns \n {array_de_uns}")
print(f"O tipo da minha matriz é: {array_de_uns.dtype}")

Esta é minha matriz de uns 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
O tipo da minha matriz é: int32


##np.empty

In [51]:
array_aleatorio = np.empty((6,3), dtype = np.int16) ## Para criar uma matriz com valores aleatórios, aproximados ao vazio. 
print(f"Este é a minha matriz aleatória \n {array_aleatorio}")

Este é a minha matriz aleatória 
 [[ -3488 -20115  22018]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]]


##np.arange

In [56]:
array_gerado = np.arange(5,100,10) ## vai criar uma matriz a partir de 5 até 100 em 2 e 2. (começo,fim,intervalo)
print(f"O array gerado é \n {array_gerado}")

O array gerado é 
 [ 5 15 25 35 45 55 65 75 85 95]


In [67]:
#x = np.random.randint(100) ## Vai gerar um valor inteiro aleatório até 100 
#print(x) ## é preciso printar o valor de X para que seja colocado no arange
array_gerado = np.arange(5,10,2,dtype = np.float32).reshape(3,5) ## vai criar uma matriz a partir de 5 até o valor que foi colocado em "X" em 2 e 2. (começo,fim,intervalo)
print(f"O array gerado é \n {array_gerado}")

ValueError: ignored