<a href="https://colab.research.google.com/github/HugocamposL3/Linguagem-Python-Para-Data-Science/blob/main/Aula%206%20de%20LPP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Aula 06 importação de biblioteca


## Exemplo 1

In [2]:
#Importação da Biblioteca
import numpy as np ## Importei a biblioteca e dei nomenclatura como 'np'

In [3]:
novo_array = np.array([[1,2,3],[4,5,6]]) # Para criar uma matriz com 2 vetores e 2 dimensões
print("abaixo está o seu array")
print(novo_array)

abaixo está o seu array
[[1 2 3]
 [4 5 6]]


##Ndim

In [4]:
print(f"Esse é um ndarray com {novo_array.ndim} dimensões")

Esse é um ndarray com 2 dimensões


##Shape

In [5]:
print(f"As dimensões desse ndarray possuem os seguintes tamanhos: {novo_array.shape}") # Para saber o tamanho do meu array 
print(f"Esse ndarray tem: {novo_array.shape[0]} Linhas e {novo_array.shape[1]} Colunas") # Para selecionar uma parte dessa tupla que o .shape vai me mostrar 

As dimensões desse ndarray possuem os seguintes tamanhos: (2, 3)
Esse ndarray tem: 2 Linhas e 3 Colunas


##Size

In [6]:
print(f"Ao todo, esse ndarray contem {novo_array.size} elementos") # Quantidade de elementos que você vai ter no seu array

Ao todo, esse ndarray contem 6 elementos


##dtype

In [7]:
print(f"Os elementos presentes nesse ndarray: {novo_array.dtype}") # "int64" é um inteiro com 64 bits

Os elementos presentes nesse ndarray: int64


## itemsize

In [8]:
print(f"Os elementos presentes nesse array ocupam {novo_array.itemsize} bytes")

Os elementos presentes nesse array ocupam 8 bytes


## Exemplo 2

##Convertendo um tupla para array 

In [9]:
array_tuplas = np.array([(1,2,3),(4,5,6)])
print(f"A nosso array de tuplas é composta por \n{array_tuplas}") ## Isso é importante para que ninguém mude os valores iniciais do seu array.

A nosso array de tuplas é composta por 
[[1 2 3]
 [4 5 6]]


In [10]:
array_lista = np.array([[1,2,3], [4,5,6]])
print(f"a nossa array de lista é composta por \n {array_lista}")

a nossa array de lista é composta por 
 [[1 2 3]
 [4 5 6]]


## Exemplo 3

##np.zeros

In [11]:
array_zerado = np.zeros((3,4)) ## Para criar um array somente com zeros com 3 linhas e 4 colunas
print(f"Este é minha matriz de zeros \n {array_zerado}")
print(f"O tipo da minha matriz é: {array_zerado.dtype}")

Este é minha matriz de zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
O tipo da minha matriz é: float64


##np.ones

In [12]:
array_de_uns = np.ones((5,2),dtype = np.int32) ## Tranformando float para int
print(f"Esta é minha matriz de uns \n {array_de_uns}")
print(f"O tipo da minha matriz é: {array_de_uns.dtype}")

Esta é minha matriz de uns 
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
O tipo da minha matriz é: int32


##np.empty

In [13]:
array_aleatorio = np.empty((6,3), dtype = np.int16) ## Para criar uma matriz com valores aleatórios, aproximados ao vazio. 
print(f"Este é a minha matriz aleatória \n {array_aleatorio}")

Este é a minha matriz aleatória 
 [[-17760  -8302  21857]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]
 [     0      0      0]]


##np.arange

In [14]:
array_gerado = np.arange(5,100,10) ## vai criar uma matriz a partir de 5 até 100 em 2 e 2. (começo,fim,intervalo)
print(f"O array gerado é \n {array_gerado}")

O array gerado é 
 [ 5 15 25 35 45 55 65 75 85 95]


In [15]:
x = np.random.randint(100) ## Vai gerar um valor inteiro aleatório até 100 
print(x) ## é preciso printar o valor de X para que seja colocado no arange
array_gerado = np.arange(0,4,1).reshape(4,1) ## vai criar uma matriz a partir de 5 até o valor que foi colocado em "X" em 2 e 2. (começo,fim,intervalo)
print(f"O array gerado é \n {array_gerado}")

89
O array gerado é 
 [[0]
 [1]
 [2]
 [3]]


## Exemplo 4


##Operações com Arrays

In [16]:
##Subtração
array_inicial = np.array ([[499.50, 25.00, 35.48],[350.15, 30.12, 17.3]])
array_resultado = array_inicial - 2
print("O ndarray resultado após a operação de subtração é:")
print(array_resultado)


O ndarray resultado após a operação de subtração é:
[[497.5   23.    33.48]
 [348.15  28.12  15.3 ]]


In [17]:
## Multiplicação
array_resultado = array_inicial * 2
print("O ndarray resultado após a operação da Multiplicação é:")
print(array_resultado)

O ndarray resultado após a operação da Multiplicação é:
[[999.    50.    70.96]
 [700.3   60.24  34.6 ]]


In [18]:
##Exponenciação
array_resultado = array_inicial ** 2
print("O ndarray resultado após a operação da Exponenciação é:")
print(array_resultado)

O ndarray resultado após a operação da Exponenciação é:
[[249500.25      625.       1258.8304]
 [122605.0225    907.2144    299.29  ]]


In [19]:
##Comparação de Valores
array_resultado = array_inicial > 10
print("O ndarray resultado após a operação da Exponenciação é:")
print(array_resultado)

O ndarray resultado após a operação da Exponenciação é:
[[ True  True  True]
 [ True  True  True]]


In [33]:
##Operação entre Vetores
array_a = np.array([1,2])
array_b = np.array([3,5])

In [27]:
##Soma
soma = array_a + array_b
print(soma)

[4 7]


In [28]:
##Multiplicação
multiplicacao = array_a * array_b
print(multiplicacao)

[ 3 10]


In [29]:
## Multiplicação de Vetores
multiplicacao = array_a @ array_b
print(multiplicacao)

13


##.Sum()

In [38]:
##Soma dos elementos internos
array_a.sum() ## ou sum(array_a) para soma de todos os elementos
array_a.sum(axis=0)

17

##.Min()

In [ ]:
##Menor elemento o vetor
array_b.min()


##.Max()

In [37]:
##Maior elemento o vetor
array_b.max()

5